docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Introduction: intro.md
site_name: Component Name Goes Here
site_description: 'Component Description goes here'
repo_url: 'https://github.com/zendframework/zend-expressive-swoole'
copyright: 'Copyright (c) 2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
